services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: donghang_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/valkey/data:/data
  donghang-ai:
    image: donghangbank/donghang-ai:latest
    container_name: donghang-ai
    restart: always
    ports:
      - "8000:8000"
