spring:
  datasource:
    driver-class-name: ${MYSQL_DATASOURCE_DRIVER}
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}

  jpa:
    show-sql: ${MYSQL_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${MYSQL_JPA_DDL_AUTO}